theme="material-design"
baseurl = "http://varunksaini.com"
languageCode = "en-us"
title = "I am an Engineer"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "varunksaini" # optional
copyright = "© 2015 Copyright Text"

[params]
  description = "go get life" # optional
  twitter = "varunksaini" # optional
  github = "varun06" # optional
  facebook = "varunsaini" # optional
  gplus = "varunksaini" # optional
  linkedin = "varunksaini" # optional
  headerCover = "files/me.jpg" # optional
  footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-42065254-1" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
