baseurl = "https://varunksaini.com/"
languageCode = "en-US"
title = "Varun Saini"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "self.png"
  author = "Varun Kumar"
  description = "personal blog"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "varun06"
  LinkedIn      = "varunksaini"
  Stackoverflow = "varunksaini"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "reading list"
  identifier = "reading"
  weight = 200
  url = "/reading/"
[[menu.main]]
  name = "go meetup videos"
  identifier = "meetup"
  weight = 300
  url = "/meetup/"
