baseurl = "https://varunksaini.com/"
languageCode = "en-US"
title = "Varun Saini"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "self.png"
  author = "Varun Saini"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "varun06"
  Email         = "email@example.com"
  Twitter       = "varunksaini"
  LinkedIn      = "varunksaini"
  Stackoverflow = "varunksaini"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "reading"
  identifier = "reading"
  weight = 200
  url = "/reading/"
[[menu.main]]
  name = "meetup videos"
  identifier = "videos"
  weight = 300
  url = "/videos/"
